### ISSUE TITLE
Fabric Support

### ISSUE THREAD

**Issue by DanielRamp** [Ultreon/exit-confirmation#3]
It looks like this mod is forge only?
How difficult is it to port this mod to fabric (and 1.19+)?

I know there are other mods but they have some disadvantages:
- [QuitConfirm](https://www.curseforge.com/minecraft/mc-mods/quitconfirm) -> **not open source**
- [Quit Confirm](https://www.curseforge.com/minecraft/mc-mods/quit-confirm) -> **only for mc 1.12.2**

**Comment by Qboi123** [comment]
I could try, it's not a large mod.

**Comment by Qboi123** [comment]
Successfully ported to Fabric 1.19.2: https://www.curseforge.com/minecraft/mc-mods/exit-confirmation/files/3981533

**Comment by DanielRamp** [comment]
Thank you for that quick development. This is great.

Sadly I don't play in 1.19.1 and above, but just 1.19.
Is there also a 1.19 (1.19.0) variant?

I think it is compatible but when "installed" the fabric loader reports a incompatible mod set.
> Replace 'Minecraft' (minecraft) 1.19 with any version between 1.19.2 (inclusive) and 1.20- (exclusive).

detailed error:
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install forgeconfigapiport, version 4.2.6 or later.
	 - Replace 'Minecraft' (minecraft) 1.19 with any version between 1.19.2 (inclusive) and 1.20- (exclusive).
Unmet dependency listing:
	 - Mod 'Exit Confirmation' (exit_confirm) 2.0.0 requires any version between 1.19.2 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	 - Mod 'Exit Confirmation' (exit_confirm) 2.0.0 requires version 4.2.6 or later of forgeconfigapiport, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
